language: node_js
node_js:
- '0.11'
before_install: 
install:
- npm install
before_script:
- npm link .
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
env:
  global:
    secure: GaHmtgfMX4vgfIiD7Ecnk5uFfyMvbB7XHxjS5E5aw3zdsPsreAgD1COcUipIYN73fIeytUAmNpRbwwt7KzbOXb+YSDGEi53SuswiJ67gpFAcOOroVO0qsHYb1r8/VMiGnb5kcKDBx8/fGETqJRqOBlkq4wsrdVvysIei1938xI3YwAb4KpWJj0F1CcUbEKObBhJq1jBfqr8ofpDA+0fxqnW1rM2Nai2lhOGnG4bQpu86qsEKNEukfRGahbuygvICL603X8coPVInfUBLzjEGghhGGoKJmaJB9CabHSjiu2ufwyi+H5EeW9Um1RnIzsMTpBPOg/TrZ6fGJGyaPfrasn6chUv1LstmtppTX18jXzM2HkctNa2untbD2ZtmofNBPUh9jtY9jKep7R9GCZUsjTZOQJs4sr9F5Zgr3BCKzETh3BvrD55RxXmoXqE8L20mWKhFBDhj5UG+Wy0cTa+lTHk9CggW3+s9Hgv3KwQLw/Pko4Ft3tFxoKYHVellRqdIQtpqGh7WKklPOI1C+U/jZksAoAQSBU55Y/RPR/sq/EeoW/bYj35NFMgk7b8ETNn81JCcNdhpk5A73a85Sm+QbOSbYqDPStalsAt/zKjL3nEffVM11iYrTJgC2BMwzQ79rQYsFRSWGKJSmyy9TTjD/xwVHqKS6+e/AtTmW0gs3ww=
